---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guard-system

resources:
- namespace.yaml
- serviceaccount.yaml
- rbac.yaml
- configmap.yaml
- deployment.yaml
- cronjob.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize

images:
- name: ghcr.io/adickinson72/guard
  newName: ghcr.io/adickinson72/guard
  newTag: v0.2.0
